### ISSUE TITLE
grunt stops working after running notobo config.js

### ISSUE THREAD

**Issue by essekia** [jrburke/notobo#5]
After running
`notobo config.js`

grunt stops working. And when running grunt, I get

```
ReferenceError: define is not defined
    at Object.<anonymous> (/Users/Pauple/Websites/elementary/wp-content/plugins/elementary/node_modules/grunt.js:1:63)
```
Any thoughts?

**Comment by jrburke** [comment]
It sounds like you have grunt installed in the same node_modules that you are using for your front end dependencies that notobo wants to modify. Right now notobo will modify all the modules in the node_modules directory.

You can see https://github.com/jrburke/notobo-example as an example project that has the top level node_modules used for command line scripts/things that should run in node, but the app/node_modules is used for the front end app and its dependencies that will be modified by notobo.

Closing as this is the expected structure for using notobo, separating the node-run command line tools from the front end dependencies.

**Comment by essekia** [comment]
Thanks for the response, @jrburke
