### ISSUE TITLE
Could not convert: Unexpected token

### ISSUE THREAD

**Issue by doliver3** [jrburke/notobo#7]
As far as I can tell, using a webpack module with lots of dependencies within a requirejs project is very impractical and nearly impossible.  I'm on a team with a product primarily using requirejs but we need to use large angular components from another team built with a webpack build that used npm for its dependencies.  There are hundreds of dependencies needed and those have nested dependencies.  

So far we haven't been able to get those project's webpack build output js to load within our requirejs project. It keeps 404'ing out on more and more nested dependencies. Get past one dependency and more are needed. Also it seems like maintaining all these dependencies one by one would be quite a massive tedious task every time that they update their dependency versions in their npm builds we would need to the manually download each dependency and configure it just right so requirejs could understand the dependencies. This problem makes using requirejs very impractical. 

In any case I was hoping this notobo library would let us manage the list of dependencies with npm so we could just refresh the list of dependencies from their project in our project, run npm install in our project, and then be able to use the updated dependencies within requirejs so their build would load in our requirejs project.

However, I've had no luck so far with this notobo utility either.  It seems to fail to convert most files. 

I'll share an example with just one dependency below but on our project there were hundreds of similar errors where notobo had no idea what to do and threw this 'Unexpected token' error. From the error I thought it was an unexpected less than sign < but when I open many of the files there is no less than sign on the line so Notobo must have an issue with something else, but there was nothing unusual about the files I looked at.  

Do you have any solutions for this problem?

```
npm install chance --save
npm run-script notobo
Could not convert: node_modules\asn1\test.js, so skipping it. Error was: Error: Line 1: Unexpected token (
```

I think you would find if you take any typical Angular project these days, Notobo is not really handling them. Perhaps you could try testing with some larger projects?

**Comment by jrburke** [comment]
The particular file mentioned looks like a test file, which may not be valid JS. Also, [code that needs to be transpiled will also not work with notobo](https://github.com/jrburke/notobo#package-x-doesnt-work), that includes code that needs babel to transpile.

No plans to support those cases either. This was a tool made for plain ES5 CommonJS modules.

Hopefully the webpack builds can be complete builds of the dependencies in them, but I can imagine that may be hard in some cases.

If the submodules all call the AMD `define()` to register, then something like [bundles config](http://requirejs.org/docs/api.html#config-bundles) may help. However, I did not think that was how webpack bundling worked.

End result, it sounds like the npm packages that are required may need transpiling to properly work, so notobo will not be able to help with that case. Perhaps if ES5 versions of the modules are created first it may work, but I can see that as also difficult to pull off, each package may have its own type of transpiler or transpiler settings that would be hard to make a generic tool.
